baseurl = "https://blog.cyberjake.xyz/"
title = "Cyb3r Jak3 - Tech Blog"
canonifyurls = true
paginate = 7
theme = ["github.com/chipzoller/hugo-clarity"]

enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "index"
  [outputFormats.JSON]
    mediatype = "application/json"
    baseName = "index"