image: ruby

stages:
 - setup
 - test


setup:
  stage: setup
  cache:
    paths:
      - vendor/bundle
  script:
  - gem install bundler
  - bundle install --path vendor/bundle
  artifacts:
    paths:
      - vendor/
      - .bundle/


build:
  cache:
    paths:
      - vendor/bundle
  stage: setup
  artifacts:
    paths:
      - _site
      - vendor/
  script:
    - bundle exec jekyll build

test:
  stage: test
  script:
    - bundle exec htmlproofer ./_site --url-ignore "/#.*/" --disable_external
  dependencies:
    - build
    - setup

