image: ruby

stages:
  - build
  - deploy

setup:
  stage: build
  cache:
    paths:
      - vendor/bundle
  script:
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site/ --url-ignore "/#.*/" --disable_external


deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: https://blog.jwhite.network
  only:
  - master

