image: ruby

stages:
 - build
 - test

build:
  stage: build
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - _site
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  script:
    - bundle exec htmlproofer ./_site --url-ignore "/#.*/" --disable_external
  dependencies:
    - build
