image: ruby:2.7
include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml


stages:
 - build
 - test
 - deploy
 - clear


build:
  cache:
    paths:
      - vendor/bundle
  stage: build
  artifacts:
     paths:
     - /builds/Cyb3r-Jak3/blog/_site/* 
  before_script:
    - bundle config set path vendor/bundle
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build

test:
  cache:
    paths:
      - vendor/bundle
  stage: test
  before_script:
    - gem install bundler
    - bundle config set path vendor/bundle
    - bundle install
  script:
    - bundle exec htmlproofer /builds/Cyb3r-Jak3/blog/_site/ --url-ignore "/#.*/" --disable_external

html5validator:
  stage: test
  image: cyb3rjak3/html5validator:pypi
  script:
    - html5validator --root _site/ --format json --log INFO --also-check-css --ignore-re Attribute "built"


.deploy:
  stage: deploy
  image: cyb3rjak3/docker-curl-ssh
  environment:
    name: Self_Host
    url: https://blog.jwhite.network
  before_script:
   - eval $(ssh-agent -s)
   - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - cat $SSH_KNOWN > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
  script:
  - scp -rp -P 2222 /builds/Cyb3r-Jak3/blog/_site/*  $DeployUser@$ServerIP:$RPath

deploy_manual:
  extends: .deploy
  when: manual
  except:
   - schedules

deploy_schedule:
  extends: .deploy
  only:
   - schedules

Clear_Cache:
  image: cyb3rjak3/docker-curl-ssh
  stage: clear
  needs:
  - deploy_manual
  script:
    - >
      curl -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE/purge_cache" -H "$API_KEY" -H "Content-Type: application/json"  --data '{"files":["https://blog.jwhite.network/*"]}'