image: ruby

setup:
  cache:
    paths:
      - vendor/bundle
  script:
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site/ --url-ignore "/#.*/" --disable_external
