image: ruby
include:
  template: Dependency-Scanning.gitlab-ci.yml


cache:
  paths:
    - vendor/bundle

stages:
 - build
 - test
 - deploy


build:
  stage: build
  artifacts:
     paths:
     - /builds/jwhite1st/blog/_site/* 
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  dependencies:
  - build
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec htmlproofer /builds/jwhite1st/blog/_site/ --url-ignore "/#.*/" --disable_external

deploy:
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
   - eval $(ssh-agent -s)
   - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan -p 2222 $ServerIP > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
  stage: deploy
  dependencies:
   - build
   - test
  script:
  - scp -rp -P 2222 /builds/jwhite1st/blog/_site/*  $DeployUser@$ServerIP:$RPath
  environment:
    name: Self_Host
    url: https://blog.jwhite.network
  when: manual
  only:
   - master
   - schedules
