image: ruby

cache:
  paths:
    - vendor/bundle

stages:
 - build
 - test
 - deploy

before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

build:
  stage: build
  artifacts:
     paths:
     - /builds/jwhite1st/blog/_site/* 
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  dependencies:
  - build
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec htmlproofer /builds/jwhite1st/blog/_site/ --url-ignore "/#.*/" --disable_external

deploy:
  stage: deploy
  dependencies:
   - build
   - test
  script:
  - echo "Made it to deployment"
  environment:
    name: Self_Host
    url: https://blog.jwhite.network
  when: manual
  only:
   - master
