image: ruby

cache:
  paths:
    - vendor/bundle

stages:
 - build
 - test
 - deploy



build:
  stage: build
  artifacts:
     paths:
     - /builds/jwhite1st/blog/_site/* 
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  dependencies:
  - build
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec htmlproofer /builds/jwhite1st/blog/_site/ --url-ignore "/#.*/" --disable_external

deploy:
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
   - eval $(ssh-agent -s)
   - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
   - mkdir -p ~/.ssh/known_hosts
   - echo "$SSH_REMOTE_KEY" >> ~/.ssh/known_hosts
  stage: deploy
  dependencies:
   - build
   - test
  script:
  - chmod 644 ~/.ssh/known_hosts
  - ssh deploy@$ServerIP:2222
  environment:
    name: Self_Host
    url: https://blog.jwhite.network
  when: manual
  only:
   - master
