image: ruby

stages:
 - setup
 - test


setup:
  stage: setup
  cache:
    paths:
      - vendor/bundle
  script:
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec jekyll build
  artifacts:
    paths:
      - vendor/**
      - _site/**

test:
  stage: test
  script:
    - ls
    - bundle exec htmlproofer ./_site/ --url-ignore "/#.*/" --disable_external
  dependencies:
    - setup

