image: ruby

stages:
 - setup
 - build
 - test

setup:
  cache:
    path:
      vendor/bundle
  script:
  - gem install bundler
  - bundle install --path vendor/bundle

build:
  stage: build
  artifacts:
    paths:
      - _site
  script:
    - bundle exec jekyll build
  dependencies:
    - setup

test:
  stage: test
  script:
    - bundle exec htmlproofer ./_site --url-ignore "/#.*/" --disable_external
  dependencies:
    - build
