image: ruby

cache:
  paths:
    - vendor/bundle

stages:
 - build
 - test
 - deploy

before_script:
 - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
 - eval $(ssh-agent -s)
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

build:
  stage: build
  artifacts:
     paths:
     - /builds/jwhite1st/blog/_site/* 
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  dependencies:
  - build
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec htmlproofer /builds/jwhite1st/blog/_site/ --url-ignore "/#.*/" --disable_external

deploy:
  stage: deploy
  dependencies:
   - build
   - test
  script:
  - echo "Made it to deployment"
  - ssh deploy@$ServerIP:2222
  
  environment:
    name: Self_Host
    url: https://blog.jwhite.network
  when: manual
  only:
   - master
