image: ruby

before_script:
  - gem install bundler
  - bundle install --path vendor/bundle

build:
  script:
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site --url-ignore "/#.*/" --disable_external
