image: ruby

before_script:
  - gem install bundler
  - bundle install --path vendor/bundle

jekyll:
  - bundle exec jekyll build

htmlproofer:
  - bundle exec htmlproofer ./_site --url-ignore "/#.*/" --disable_external
