image: ruby

stages:
 - build
 - test

build:
  stage: build
  cache:
    paths:
     - vendor/bundle
  artifacts:
     paths:
     - /builds/jwhite1st/blog/_site/* 
  script:
    - gem install bundler
    - bundle install --path vendor/bundle
    - bundle exec jekyll build

test:
  stage: test
  dependencies:
  - build
  script:
    - gem install bundler
    - bundle exec htmlproofer /builds/jwhite1st/blog/_site/ --url-ignore "/#.*/" --disable_external