version: '3.9'

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MOTD: "Hello via Cloudflared"
    volumes:
      - ./minecraft_data:/data

  cloudflared:
      image: cloudflare/cloudflared:2025.8.1@sha256:b77d84e8704db38db22c22661cf7e56468c526e3a6a5fe9c8b7c151452fa1472
      user: root
      command: tunnel run
      volumes:
          - './cloudflared:/etc/cloudflared'