title: Cyb3r Jak3 - Tech Blog
description: >
  Welcome to tech blog where I mostly rant about things cyber related. I have tutorials and walkthroughs here as well.
permalink: ':title/'
url: "https://blog.cyberjake.xyz"

author: Cyb3r Jak3 
author-img: about/about.webp
about-author: I enjoy learning about new technologies and exploring new ways of doing things. I love discovering new platforms and new ways of doing things and using technology to its fullest potential.
social-twitter: Cyb3r_Jak3
social-github: Cyb3r-Jak3
social-email: connect@cyberjake.xyz

# Disqus
# discus-identifier: jtech-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

include: ["_headers", ]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]