name: Lint

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ hashFiles('**/Gemfile.lock') }}

      - name: Setup Environment
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Site
        run: bundle exec jekyll build --source blog/ --destination public/
      
      - name: HTML5 Validation
        uses: Cyb3r-Jak3/html5validator-action@v0.4.4
        with:
            root: public/
            format: json
            css: true
            log_level: INFO
            extra: --ignore-re Attribute "built"