name: Codespell
on:
  push:
    branches:
    - "**"
    paths:
      - "content/**"
      - ".github/workflows/spellcheck.yml"

jobs:
  spell-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Spell-Checking
      uses: codespell-project/actions-codespell@master
      with:
        path: content/post/
        check_filenames: true

